spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  application:
    name: SWYP_team1_back
  datasource:
    password: swypswyp1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: swypteam1
    url: jdbc:mysql://swyp-team1-back.cb6aokwc8vaf.ap-northeast-2.rds.amazonaws.com:3306/swygTeam1?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul

server:
  shutdown: graceful
  servlet:
    context-path: /
  port: '8080'
logging:
  level:
    org:
      hibernate:
        type:
          nodeValue: trace
          descriptor:
            sql: trace
      springframework:
        web: debug
        security: debug


cloud:
  aws:
    s3:
      bucket: swyp-team1-s3-bucket
    credentials:
      accessKey: AKIA5FTZEK3JYQYPYBNN
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  secret:
    key: UlYth+E49WB6dlTGdGG2Ll0c8PBcFjgbqt+IOP/Z6F7MlpWB04rsL9iIc9GGlnWVFV1PmWqmp9tDkox4kJHz1Q==

security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: 5d3ed4c53f6081a9a1503e178dfdfaeb
          client-secret: SazkBcme6hi3TkyhRBBps3Hl0G7rMfcP
          redirect-uri: "http://localhost:8080/api/user/login/kakao"
          authorization-grant-type: authorization_code
          scope: profile_nickname,  account_email
          client-authentication-method: POST
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id




